/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as OnboardingDoneRouteImport } from './routes/onboarding-done'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as SIdRouteImport } from './routes/s.$id'
import { Route as AppUsageRouteImport } from './routes/app.usage'
import { Route as AppTeamRouteImport } from './routes/app.team'
import { Route as AppSubscriptionRouteImport } from './routes/app.subscription'
import { Route as AppSitesStudioRouteImport } from './routes/app.sites-studio'
import { Route as AppSitePreviewRouteImport } from './routes/app.site-preview'
import { Route as AppSiteRouteImport } from './routes/app.site'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppPublishRouteImport } from './routes/app.publish'
import { Route as AppProjectsRouteImport } from './routes/app.projects'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppNodesRouteImport } from './routes/app.nodes'
import { Route as AppMoodboardsRouteImport } from './routes/app.moodboards'
import { Route as AppMediaStudioRouteImport } from './routes/app.media-studio'
import { Route as AppMediaRouteImport } from './routes/app.media'
import { Route as AppLoraRouteImport } from './routes/app.lora'
import { Route as AppGuidesRouteImport } from './routes/app.guides'
import { Route as AppFactoryRouteImport } from './routes/app.factory'
import { Route as AppCreateRouteImport } from './routes/app.create'
import { Route as AppCommunityRouteImport } from './routes/app.community'
import { Route as AppBillingRouteImport } from './routes/app.billing'
import { Route as AppAssistantsStudioRouteImport } from './routes/app.assistants-studio'
import { Route as AppAssetsRouteImport } from './routes/app.assets'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppToolsIndexRouteImport } from './routes/app.tools.index'
import { Route as AppToolsToolIdRouteImport } from './routes/app.tools.$toolId'
import { Route as AppStudioVoicesRouteImport } from './routes/app.studio.voices'
import { Route as AppStudioVideoRouteImport } from './routes/app.studio.video'
import { Route as AppStudioRealtimeRouteImport } from './routes/app.studio.realtime'
import { Route as AppStudioQueueRouteImport } from './routes/app.studio.queue'
import { Route as AppStudioImageRouteImport } from './routes/app.studio.image'
import { Route as AppStudioEnhancerRouteImport } from './routes/app.studio.enhancer'
import { Route as AppStudioAvatarsRouteImport } from './routes/app.studio.avatars'
import { Route as AppProjectsIdRouteImport } from './routes/app.projects.$id'
import { Route as AppMoodboardsIdRouteImport } from './routes/app.moodboards.$id'
import { Route as AppKnowledgeIdRouteImport } from './routes/app.knowledge.$id'
import { Route as AppAssistantNewRouteImport } from './routes/app.assistant.new'
import { Route as AppAssistantIdRouteImport } from './routes/app.assistant.$id'
import { Route as AppAssistantIdLeadsRouteImport } from './routes/app.assistant.$id.leads'
import { Route as AppAssistantIdConnectRouteImport } from './routes/app.assistant.$id.connect'
import { Route as AppAssistantIdChatTestRouteImport } from './routes/app.assistant.$id.chat-test'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingDoneRoute = OnboardingDoneRouteImport.update({
  id: '/onboarding-done',
  path: '/onboarding-done',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const SIdRoute = SIdRouteImport.update({
  id: '/s/$id',
  path: '/s/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsageRoute = AppUsageRouteImport.update({
  id: '/app/usage',
  path: '/app/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/app/team',
  path: '/app/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSubscriptionRoute = AppSubscriptionRouteImport.update({
  id: '/app/subscription',
  path: '/app/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSitesStudioRoute = AppSitesStudioRouteImport.update({
  id: '/app/sites-studio',
  path: '/app/sites-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSitePreviewRoute = AppSitePreviewRouteImport.update({
  id: '/app/site-preview',
  path: '/app/site-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSiteRoute = AppSiteRouteImport.update({
  id: '/app/site',
  path: '/app/site',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/app/settings',
  path: '/app/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPublishRoute = AppPublishRouteImport.update({
  id: '/app/publish',
  path: '/app/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/app/projects',
  path: '/app/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNodesRoute = AppNodesRouteImport.update({
  id: '/app/nodes',
  path: '/app/nodes',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMoodboardsRoute = AppMoodboardsRouteImport.update({
  id: '/app/moodboards',
  path: '/app/moodboards',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMediaStudioRoute = AppMediaStudioRouteImport.update({
  id: '/app/media-studio',
  path: '/app/media-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMediaRoute = AppMediaRouteImport.update({
  id: '/app/media',
  path: '/app/media',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLoraRoute = AppLoraRouteImport.update({
  id: '/app/lora',
  path: '/app/lora',
  getParentRoute: () => rootRouteImport,
} as any)
const AppGuidesRoute = AppGuidesRouteImport.update({
  id: '/app/guides',
  path: '/app/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFactoryRoute = AppFactoryRouteImport.update({
  id: '/app/factory',
  path: '/app/factory',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCreateRoute = AppCreateRouteImport.update({
  id: '/app/create',
  path: '/app/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCommunityRoute = AppCommunityRouteImport.update({
  id: '/app/community',
  path: '/app/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/app/billing',
  path: '/app/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAssistantsStudioRoute = AppAssistantsStudioRouteImport.update({
  id: '/app/assistants-studio',
  path: '/app/assistants-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAssetsRoute = AppAssetsRouteImport.update({
  id: '/app/assets',
  path: '/app/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/app/admin',
  path: '/app/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppToolsIndexRoute = AppToolsIndexRouteImport.update({
  id: '/app/tools/',
  path: '/app/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppToolsToolIdRoute = AppToolsToolIdRouteImport.update({
  id: '/app/tools/$toolId',
  path: '/app/tools/$toolId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStudioVoicesRoute = AppStudioVoicesRouteImport.update({
  id: '/app/studio/voices',
  path: '/app/studio/voices',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStudioVideoRoute = AppStudioVideoRouteImport.update({
  id: '/app/studio/video',
  path: '/app/studio/video',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStudioRealtimeRoute = AppStudioRealtimeRouteImport.update({
  id: '/app/studio/realtime',
  path: '/app/studio/realtime',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStudioQueueRoute = AppStudioQueueRouteImport.update({
  id: '/app/studio/queue',
  path: '/app/studio/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStudioImageRoute = AppStudioImageRouteImport.update({
  id: '/app/studio/image',
  path: '/app/studio/image',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStudioEnhancerRoute = AppStudioEnhancerRouteImport.update({
  id: '/app/studio/enhancer',
  path: '/app/studio/enhancer',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStudioAvatarsRoute = AppStudioAvatarsRouteImport.update({
  id: '/app/studio/avatars',
  path: '/app/studio/avatars',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectsIdRoute = AppProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppMoodboardsIdRoute = AppMoodboardsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppMoodboardsRoute,
} as any)
const AppKnowledgeIdRoute = AppKnowledgeIdRouteImport.update({
  id: '/app/knowledge/$id',
  path: '/app/knowledge/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAssistantNewRoute = AppAssistantNewRouteImport.update({
  id: '/app/assistant/new',
  path: '/app/assistant/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAssistantIdRoute = AppAssistantIdRouteImport.update({
  id: '/app/assistant/$id',
  path: '/app/assistant/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAssistantIdLeadsRoute = AppAssistantIdLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppAssistantIdRoute,
} as any)
const AppAssistantIdConnectRoute = AppAssistantIdConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => AppAssistantIdRoute,
} as any)
const AppAssistantIdChatTestRoute = AppAssistantIdChatTestRouteImport.update({
  id: '/chat-test',
  path: '/chat-test',
  getParentRoute: () => AppAssistantIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/onboarding-done': typeof OnboardingDoneRoute
  '/plan': typeof PlanRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRoute
  '/app/assets': typeof AppAssetsRoute
  '/app/assistants-studio': typeof AppAssistantsStudioRoute
  '/app/billing': typeof AppBillingRoute
  '/app/community': typeof AppCommunityRoute
  '/app/create': typeof AppCreateRoute
  '/app/factory': typeof AppFactoryRoute
  '/app/guides': typeof AppGuidesRoute
  '/app/lora': typeof AppLoraRoute
  '/app/media': typeof AppMediaRoute
  '/app/media-studio': typeof AppMediaStudioRoute
  '/app/moodboards': typeof AppMoodboardsRouteWithChildren
  '/app/nodes': typeof AppNodesRoute
  '/app/profile': typeof AppProfileRoute
  '/app/projects': typeof AppProjectsRouteWithChildren
  '/app/publish': typeof AppPublishRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/site': typeof AppSiteRoute
  '/app/site-preview': typeof AppSitePreviewRoute
  '/app/sites-studio': typeof AppSitesStudioRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/app/team': typeof AppTeamRoute
  '/app/usage': typeof AppUsageRoute
  '/s/$id': typeof SIdRoute
  '/app/': typeof AppIndexRoute
  '/app/assistant/$id': typeof AppAssistantIdRouteWithChildren
  '/app/assistant/new': typeof AppAssistantNewRoute
  '/app/knowledge/$id': typeof AppKnowledgeIdRoute
  '/app/moodboards/$id': typeof AppMoodboardsIdRoute
  '/app/projects/$id': typeof AppProjectsIdRoute
  '/app/studio/avatars': typeof AppStudioAvatarsRoute
  '/app/studio/enhancer': typeof AppStudioEnhancerRoute
  '/app/studio/image': typeof AppStudioImageRoute
  '/app/studio/queue': typeof AppStudioQueueRoute
  '/app/studio/realtime': typeof AppStudioRealtimeRoute
  '/app/studio/video': typeof AppStudioVideoRoute
  '/app/studio/voices': typeof AppStudioVoicesRoute
  '/app/tools/$toolId': typeof AppToolsToolIdRoute
  '/app/tools/': typeof AppToolsIndexRoute
  '/app/assistant/$id/chat-test': typeof AppAssistantIdChatTestRoute
  '/app/assistant/$id/connect': typeof AppAssistantIdConnectRoute
  '/app/assistant/$id/leads': typeof AppAssistantIdLeadsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/onboarding-done': typeof OnboardingDoneRoute
  '/plan': typeof PlanRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRoute
  '/app/assets': typeof AppAssetsRoute
  '/app/assistants-studio': typeof AppAssistantsStudioRoute
  '/app/billing': typeof AppBillingRoute
  '/app/community': typeof AppCommunityRoute
  '/app/create': typeof AppCreateRoute
  '/app/factory': typeof AppFactoryRoute
  '/app/guides': typeof AppGuidesRoute
  '/app/lora': typeof AppLoraRoute
  '/app/media': typeof AppMediaRoute
  '/app/media-studio': typeof AppMediaStudioRoute
  '/app/moodboards': typeof AppMoodboardsRouteWithChildren
  '/app/nodes': typeof AppNodesRoute
  '/app/profile': typeof AppProfileRoute
  '/app/projects': typeof AppProjectsRouteWithChildren
  '/app/publish': typeof AppPublishRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/site': typeof AppSiteRoute
  '/app/site-preview': typeof AppSitePreviewRoute
  '/app/sites-studio': typeof AppSitesStudioRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/app/team': typeof AppTeamRoute
  '/app/usage': typeof AppUsageRoute
  '/s/$id': typeof SIdRoute
  '/app': typeof AppIndexRoute
  '/app/assistant/$id': typeof AppAssistantIdRouteWithChildren
  '/app/assistant/new': typeof AppAssistantNewRoute
  '/app/knowledge/$id': typeof AppKnowledgeIdRoute
  '/app/moodboards/$id': typeof AppMoodboardsIdRoute
  '/app/projects/$id': typeof AppProjectsIdRoute
  '/app/studio/avatars': typeof AppStudioAvatarsRoute
  '/app/studio/enhancer': typeof AppStudioEnhancerRoute
  '/app/studio/image': typeof AppStudioImageRoute
  '/app/studio/queue': typeof AppStudioQueueRoute
  '/app/studio/realtime': typeof AppStudioRealtimeRoute
  '/app/studio/video': typeof AppStudioVideoRoute
  '/app/studio/voices': typeof AppStudioVoicesRoute
  '/app/tools/$toolId': typeof AppToolsToolIdRoute
  '/app/tools': typeof AppToolsIndexRoute
  '/app/assistant/$id/chat-test': typeof AppAssistantIdChatTestRoute
  '/app/assistant/$id/connect': typeof AppAssistantIdConnectRoute
  '/app/assistant/$id/leads': typeof AppAssistantIdLeadsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/onboarding-done': typeof OnboardingDoneRoute
  '/plan': typeof PlanRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRoute
  '/app/assets': typeof AppAssetsRoute
  '/app/assistants-studio': typeof AppAssistantsStudioRoute
  '/app/billing': typeof AppBillingRoute
  '/app/community': typeof AppCommunityRoute
  '/app/create': typeof AppCreateRoute
  '/app/factory': typeof AppFactoryRoute
  '/app/guides': typeof AppGuidesRoute
  '/app/lora': typeof AppLoraRoute
  '/app/media': typeof AppMediaRoute
  '/app/media-studio': typeof AppMediaStudioRoute
  '/app/moodboards': typeof AppMoodboardsRouteWithChildren
  '/app/nodes': typeof AppNodesRoute
  '/app/profile': typeof AppProfileRoute
  '/app/projects': typeof AppProjectsRouteWithChildren
  '/app/publish': typeof AppPublishRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/site': typeof AppSiteRoute
  '/app/site-preview': typeof AppSitePreviewRoute
  '/app/sites-studio': typeof AppSitesStudioRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/app/team': typeof AppTeamRoute
  '/app/usage': typeof AppUsageRoute
  '/s/$id': typeof SIdRoute
  '/app/': typeof AppIndexRoute
  '/app/assistant/$id': typeof AppAssistantIdRouteWithChildren
  '/app/assistant/new': typeof AppAssistantNewRoute
  '/app/knowledge/$id': typeof AppKnowledgeIdRoute
  '/app/moodboards/$id': typeof AppMoodboardsIdRoute
  '/app/projects/$id': typeof AppProjectsIdRoute
  '/app/studio/avatars': typeof AppStudioAvatarsRoute
  '/app/studio/enhancer': typeof AppStudioEnhancerRoute
  '/app/studio/image': typeof AppStudioImageRoute
  '/app/studio/queue': typeof AppStudioQueueRoute
  '/app/studio/realtime': typeof AppStudioRealtimeRoute
  '/app/studio/video': typeof AppStudioVideoRoute
  '/app/studio/voices': typeof AppStudioVoicesRoute
  '/app/tools/$toolId': typeof AppToolsToolIdRoute
  '/app/tools/': typeof AppToolsIndexRoute
  '/app/assistant/$id/chat-test': typeof AppAssistantIdChatTestRoute
  '/app/assistant/$id/connect': typeof AppAssistantIdConnectRoute
  '/app/assistant/$id/leads': typeof AppAssistantIdLeadsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/landing'
    | '/login'
    | '/onboarding'
    | '/onboarding-done'
    | '/plan'
    | '/pricing'
    | '/signup'
    | '/app/admin'
    | '/app/assets'
    | '/app/assistants-studio'
    | '/app/billing'
    | '/app/community'
    | '/app/create'
    | '/app/factory'
    | '/app/guides'
    | '/app/lora'
    | '/app/media'
    | '/app/media-studio'
    | '/app/moodboards'
    | '/app/nodes'
    | '/app/profile'
    | '/app/projects'
    | '/app/publish'
    | '/app/settings'
    | '/app/site'
    | '/app/site-preview'
    | '/app/sites-studio'
    | '/app/subscription'
    | '/app/team'
    | '/app/usage'
    | '/s/$id'
    | '/app/'
    | '/app/assistant/$id'
    | '/app/assistant/new'
    | '/app/knowledge/$id'
    | '/app/moodboards/$id'
    | '/app/projects/$id'
    | '/app/studio/avatars'
    | '/app/studio/enhancer'
    | '/app/studio/image'
    | '/app/studio/queue'
    | '/app/studio/realtime'
    | '/app/studio/video'
    | '/app/studio/voices'
    | '/app/tools/$toolId'
    | '/app/tools/'
    | '/app/assistant/$id/chat-test'
    | '/app/assistant/$id/connect'
    | '/app/assistant/$id/leads'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/landing'
    | '/login'
    | '/onboarding'
    | '/onboarding-done'
    | '/plan'
    | '/pricing'
    | '/signup'
    | '/app/admin'
    | '/app/assets'
    | '/app/assistants-studio'
    | '/app/billing'
    | '/app/community'
    | '/app/create'
    | '/app/factory'
    | '/app/guides'
    | '/app/lora'
    | '/app/media'
    | '/app/media-studio'
    | '/app/moodboards'
    | '/app/nodes'
    | '/app/profile'
    | '/app/projects'
    | '/app/publish'
    | '/app/settings'
    | '/app/site'
    | '/app/site-preview'
    | '/app/sites-studio'
    | '/app/subscription'
    | '/app/team'
    | '/app/usage'
    | '/s/$id'
    | '/app'
    | '/app/assistant/$id'
    | '/app/assistant/new'
    | '/app/knowledge/$id'
    | '/app/moodboards/$id'
    | '/app/projects/$id'
    | '/app/studio/avatars'
    | '/app/studio/enhancer'
    | '/app/studio/image'
    | '/app/studio/queue'
    | '/app/studio/realtime'
    | '/app/studio/video'
    | '/app/studio/voices'
    | '/app/tools/$toolId'
    | '/app/tools'
    | '/app/assistant/$id/chat-test'
    | '/app/assistant/$id/connect'
    | '/app/assistant/$id/leads'
  id:
    | '__root__'
    | '/'
    | '/landing'
    | '/login'
    | '/onboarding'
    | '/onboarding-done'
    | '/plan'
    | '/pricing'
    | '/signup'
    | '/app/admin'
    | '/app/assets'
    | '/app/assistants-studio'
    | '/app/billing'
    | '/app/community'
    | '/app/create'
    | '/app/factory'
    | '/app/guides'
    | '/app/lora'
    | '/app/media'
    | '/app/media-studio'
    | '/app/moodboards'
    | '/app/nodes'
    | '/app/profile'
    | '/app/projects'
    | '/app/publish'
    | '/app/settings'
    | '/app/site'
    | '/app/site-preview'
    | '/app/sites-studio'
    | '/app/subscription'
    | '/app/team'
    | '/app/usage'
    | '/s/$id'
    | '/app/'
    | '/app/assistant/$id'
    | '/app/assistant/new'
    | '/app/knowledge/$id'
    | '/app/moodboards/$id'
    | '/app/projects/$id'
    | '/app/studio/avatars'
    | '/app/studio/enhancer'
    | '/app/studio/image'
    | '/app/studio/queue'
    | '/app/studio/realtime'
    | '/app/studio/video'
    | '/app/studio/voices'
    | '/app/tools/$toolId'
    | '/app/tools/'
    | '/app/assistant/$id/chat-test'
    | '/app/assistant/$id/connect'
    | '/app/assistant/$id/leads'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  OnboardingDoneRoute: typeof OnboardingDoneRoute
  PlanRoute: typeof PlanRoute
  PricingRoute: typeof PricingRoute
  SignupRoute: typeof SignupRoute
  AppAdminRoute: typeof AppAdminRoute
  AppAssetsRoute: typeof AppAssetsRoute
  AppAssistantsStudioRoute: typeof AppAssistantsStudioRoute
  AppBillingRoute: typeof AppBillingRoute
  AppCommunityRoute: typeof AppCommunityRoute
  AppCreateRoute: typeof AppCreateRoute
  AppFactoryRoute: typeof AppFactoryRoute
  AppGuidesRoute: typeof AppGuidesRoute
  AppLoraRoute: typeof AppLoraRoute
  AppMediaRoute: typeof AppMediaRoute
  AppMediaStudioRoute: typeof AppMediaStudioRoute
  AppMoodboardsRoute: typeof AppMoodboardsRouteWithChildren
  AppNodesRoute: typeof AppNodesRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
  AppPublishRoute: typeof AppPublishRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSiteRoute: typeof AppSiteRoute
  AppSitePreviewRoute: typeof AppSitePreviewRoute
  AppSitesStudioRoute: typeof AppSitesStudioRoute
  AppSubscriptionRoute: typeof AppSubscriptionRoute
  AppTeamRoute: typeof AppTeamRoute
  AppUsageRoute: typeof AppUsageRoute
  SIdRoute: typeof SIdRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAssistantIdRoute: typeof AppAssistantIdRouteWithChildren
  AppAssistantNewRoute: typeof AppAssistantNewRoute
  AppKnowledgeIdRoute: typeof AppKnowledgeIdRoute
  AppStudioAvatarsRoute: typeof AppStudioAvatarsRoute
  AppStudioEnhancerRoute: typeof AppStudioEnhancerRoute
  AppStudioImageRoute: typeof AppStudioImageRoute
  AppStudioQueueRoute: typeof AppStudioQueueRoute
  AppStudioRealtimeRoute: typeof AppStudioRealtimeRoute
  AppStudioVideoRoute: typeof AppStudioVideoRoute
  AppStudioVoicesRoute: typeof AppStudioVoicesRoute
  AppToolsToolIdRoute: typeof AppToolsToolIdRoute
  AppToolsIndexRoute: typeof AppToolsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding-done': {
      id: '/onboarding-done'
      path: '/onboarding-done'
      fullPath: '/onboarding-done'
      preLoaderRoute: typeof OnboardingDoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$id': {
      id: '/s/$id'
      path: '/s/$id'
      fullPath: '/s/$id'
      preLoaderRoute: typeof SIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/usage': {
      id: '/app/usage'
      path: '/app/usage'
      fullPath: '/app/usage'
      preLoaderRoute: typeof AppUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/team': {
      id: '/app/team'
      path: '/app/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/subscription': {
      id: '/app/subscription'
      path: '/app/subscription'
      fullPath: '/app/subscription'
      preLoaderRoute: typeof AppSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/sites-studio': {
      id: '/app/sites-studio'
      path: '/app/sites-studio'
      fullPath: '/app/sites-studio'
      preLoaderRoute: typeof AppSitesStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/site-preview': {
      id: '/app/site-preview'
      path: '/app/site-preview'
      fullPath: '/app/site-preview'
      preLoaderRoute: typeof AppSitePreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/site': {
      id: '/app/site'
      path: '/app/site'
      fullPath: '/app/site'
      preLoaderRoute: typeof AppSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/publish': {
      id: '/app/publish'
      path: '/app/publish'
      fullPath: '/app/publish'
      preLoaderRoute: typeof AppPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/projects': {
      id: '/app/projects'
      path: '/app/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/nodes': {
      id: '/app/nodes'
      path: '/app/nodes'
      fullPath: '/app/nodes'
      preLoaderRoute: typeof AppNodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/moodboards': {
      id: '/app/moodboards'
      path: '/app/moodboards'
      fullPath: '/app/moodboards'
      preLoaderRoute: typeof AppMoodboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/media-studio': {
      id: '/app/media-studio'
      path: '/app/media-studio'
      fullPath: '/app/media-studio'
      preLoaderRoute: typeof AppMediaStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/media': {
      id: '/app/media'
      path: '/app/media'
      fullPath: '/app/media'
      preLoaderRoute: typeof AppMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/lora': {
      id: '/app/lora'
      path: '/app/lora'
      fullPath: '/app/lora'
      preLoaderRoute: typeof AppLoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/guides': {
      id: '/app/guides'
      path: '/app/guides'
      fullPath: '/app/guides'
      preLoaderRoute: typeof AppGuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/factory': {
      id: '/app/factory'
      path: '/app/factory'
      fullPath: '/app/factory'
      preLoaderRoute: typeof AppFactoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/create': {
      id: '/app/create'
      path: '/app/create'
      fullPath: '/app/create'
      preLoaderRoute: typeof AppCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/community': {
      id: '/app/community'
      path: '/app/community'
      fullPath: '/app/community'
      preLoaderRoute: typeof AppCommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/app/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/assistants-studio': {
      id: '/app/assistants-studio'
      path: '/app/assistants-studio'
      fullPath: '/app/assistants-studio'
      preLoaderRoute: typeof AppAssistantsStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/assets': {
      id: '/app/assets'
      path: '/app/assets'
      fullPath: '/app/assets'
      preLoaderRoute: typeof AppAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/app/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/tools/': {
      id: '/app/tools/'
      path: '/app/tools'
      fullPath: '/app/tools/'
      preLoaderRoute: typeof AppToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/tools/$toolId': {
      id: '/app/tools/$toolId'
      path: '/app/tools/$toolId'
      fullPath: '/app/tools/$toolId'
      preLoaderRoute: typeof AppToolsToolIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/studio/voices': {
      id: '/app/studio/voices'
      path: '/app/studio/voices'
      fullPath: '/app/studio/voices'
      preLoaderRoute: typeof AppStudioVoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/studio/video': {
      id: '/app/studio/video'
      path: '/app/studio/video'
      fullPath: '/app/studio/video'
      preLoaderRoute: typeof AppStudioVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/studio/realtime': {
      id: '/app/studio/realtime'
      path: '/app/studio/realtime'
      fullPath: '/app/studio/realtime'
      preLoaderRoute: typeof AppStudioRealtimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/studio/queue': {
      id: '/app/studio/queue'
      path: '/app/studio/queue'
      fullPath: '/app/studio/queue'
      preLoaderRoute: typeof AppStudioQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/studio/image': {
      id: '/app/studio/image'
      path: '/app/studio/image'
      fullPath: '/app/studio/image'
      preLoaderRoute: typeof AppStudioImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/studio/enhancer': {
      id: '/app/studio/enhancer'
      path: '/app/studio/enhancer'
      fullPath: '/app/studio/enhancer'
      preLoaderRoute: typeof AppStudioEnhancerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/studio/avatars': {
      id: '/app/studio/avatars'
      path: '/app/studio/avatars'
      fullPath: '/app/studio/avatars'
      preLoaderRoute: typeof AppStudioAvatarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/projects/$id': {
      id: '/app/projects/$id'
      path: '/$id'
      fullPath: '/app/projects/$id'
      preLoaderRoute: typeof AppProjectsIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/app/moodboards/$id': {
      id: '/app/moodboards/$id'
      path: '/$id'
      fullPath: '/app/moodboards/$id'
      preLoaderRoute: typeof AppMoodboardsIdRouteImport
      parentRoute: typeof AppMoodboardsRoute
    }
    '/app/knowledge/$id': {
      id: '/app/knowledge/$id'
      path: '/app/knowledge/$id'
      fullPath: '/app/knowledge/$id'
      preLoaderRoute: typeof AppKnowledgeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/assistant/new': {
      id: '/app/assistant/new'
      path: '/app/assistant/new'
      fullPath: '/app/assistant/new'
      preLoaderRoute: typeof AppAssistantNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/assistant/$id': {
      id: '/app/assistant/$id'
      path: '/app/assistant/$id'
      fullPath: '/app/assistant/$id'
      preLoaderRoute: typeof AppAssistantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/assistant/$id/leads': {
      id: '/app/assistant/$id/leads'
      path: '/leads'
      fullPath: '/app/assistant/$id/leads'
      preLoaderRoute: typeof AppAssistantIdLeadsRouteImport
      parentRoute: typeof AppAssistantIdRoute
    }
    '/app/assistant/$id/connect': {
      id: '/app/assistant/$id/connect'
      path: '/connect'
      fullPath: '/app/assistant/$id/connect'
      preLoaderRoute: typeof AppAssistantIdConnectRouteImport
      parentRoute: typeof AppAssistantIdRoute
    }
    '/app/assistant/$id/chat-test': {
      id: '/app/assistant/$id/chat-test'
      path: '/chat-test'
      fullPath: '/app/assistant/$id/chat-test'
      preLoaderRoute: typeof AppAssistantIdChatTestRouteImport
      parentRoute: typeof AppAssistantIdRoute
    }
  }
}

interface AppMoodboardsRouteChildren {
  AppMoodboardsIdRoute: typeof AppMoodboardsIdRoute
}

const AppMoodboardsRouteChildren: AppMoodboardsRouteChildren = {
  AppMoodboardsIdRoute: AppMoodboardsIdRoute,
}

const AppMoodboardsRouteWithChildren = AppMoodboardsRoute._addFileChildren(
  AppMoodboardsRouteChildren,
)

interface AppProjectsRouteChildren {
  AppProjectsIdRoute: typeof AppProjectsIdRoute
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsIdRoute: AppProjectsIdRoute,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppAssistantIdRouteChildren {
  AppAssistantIdChatTestRoute: typeof AppAssistantIdChatTestRoute
  AppAssistantIdConnectRoute: typeof AppAssistantIdConnectRoute
  AppAssistantIdLeadsRoute: typeof AppAssistantIdLeadsRoute
}

const AppAssistantIdRouteChildren: AppAssistantIdRouteChildren = {
  AppAssistantIdChatTestRoute: AppAssistantIdChatTestRoute,
  AppAssistantIdConnectRoute: AppAssistantIdConnectRoute,
  AppAssistantIdLeadsRoute: AppAssistantIdLeadsRoute,
}

const AppAssistantIdRouteWithChildren = AppAssistantIdRoute._addFileChildren(
  AppAssistantIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  OnboardingDoneRoute: OnboardingDoneRoute,
  PlanRoute: PlanRoute,
  PricingRoute: PricingRoute,
  SignupRoute: SignupRoute,
  AppAdminRoute: AppAdminRoute,
  AppAssetsRoute: AppAssetsRoute,
  AppAssistantsStudioRoute: AppAssistantsStudioRoute,
  AppBillingRoute: AppBillingRoute,
  AppCommunityRoute: AppCommunityRoute,
  AppCreateRoute: AppCreateRoute,
  AppFactoryRoute: AppFactoryRoute,
  AppGuidesRoute: AppGuidesRoute,
  AppLoraRoute: AppLoraRoute,
  AppMediaRoute: AppMediaRoute,
  AppMediaStudioRoute: AppMediaStudioRoute,
  AppMoodboardsRoute: AppMoodboardsRouteWithChildren,
  AppNodesRoute: AppNodesRoute,
  AppProfileRoute: AppProfileRoute,
  AppProjectsRoute: AppProjectsRouteWithChildren,
  AppPublishRoute: AppPublishRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSiteRoute: AppSiteRoute,
  AppSitePreviewRoute: AppSitePreviewRoute,
  AppSitesStudioRoute: AppSitesStudioRoute,
  AppSubscriptionRoute: AppSubscriptionRoute,
  AppTeamRoute: AppTeamRoute,
  AppUsageRoute: AppUsageRoute,
  SIdRoute: SIdRoute,
  AppIndexRoute: AppIndexRoute,
  AppAssistantIdRoute: AppAssistantIdRouteWithChildren,
  AppAssistantNewRoute: AppAssistantNewRoute,
  AppKnowledgeIdRoute: AppKnowledgeIdRoute,
  AppStudioAvatarsRoute: AppStudioAvatarsRoute,
  AppStudioEnhancerRoute: AppStudioEnhancerRoute,
  AppStudioImageRoute: AppStudioImageRoute,
  AppStudioQueueRoute: AppStudioQueueRoute,
  AppStudioRealtimeRoute: AppStudioRealtimeRoute,
  AppStudioVideoRoute: AppStudioVideoRoute,
  AppStudioVoicesRoute: AppStudioVoicesRoute,
  AppToolsToolIdRoute: AppToolsToolIdRoute,
  AppToolsIndexRoute: AppToolsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
